version: "3"
services:

  postgres:
    container_name: prac_db
    image: postgres:12.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=root
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
