version: "3"
services:

  postgres:
    container_name: prac_db
    image: postgres:12.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=root
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  # server:
  #   container_name: server
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile.dev
  #   environment:
  #     DATABASE_URL: "postgresql://root:pass@localhost:5432/root?schema=public"
        # Structure: "postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@localhost:{POSTGRES_PORT}/{POSTGRES_DB}?schema=public"
  #   volumes:
  #     - /app/node_modules
  #     - ./server/config:/app/config
  #     - ./server/src:/app/src
  #     - ./server/test:/app/test
  #   ports:
  #     - "3001:3001"
      
  # client:
  #   container_name: client
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile.dev 
  #   volumes:
  #     - /app/node_modules
  #     - ./client/src:/app/src
  #     - ./client/public:/app/public
  #     - ./client/.env:/app/.env:ro
  #   ports:
  #     - "5173:5173"
