FROM node:20.11
RUN mkdir -p /app/config /app/src
WORKDIR /app
COPY package.json /app/package.json
COPY .env /app/.env
COPY package-lock.json /app/package-lock.json
RUN npm install
COPY . .
EXPOSE 3001

RUN npx prisma generate
CMD ["npm", "run", "dev"]